### PR TITLE
Misc: Refactor app async handling, update PR message, etc.

### LINKED ISSUE #23: Redirect index to Formidable lander
- [ ] Redirect to https://formidable.com/open-source/badges

### LINKED ISSUE #27: BUG: Async errors aren't handled.
## Reproduction

```sh
$ yarn start:dev
$ open http://127.0.0.1:3000/sauce/Havunen?labels=none
```

- **Expected**: Get a badge or an error stack trace.
- **Actual**: Page hangs.

## Work

Already begun in branch-of-branch: https://github.com/FormidableLabs/badges/compare/chore/docs-updates...bug/async-errors

### LINKED ISSUE #28: Chore: Add instructions for using aws user for needed routes in localdev.
Already set up in comments of `DEVELOPMENT.md` for work.

Options (not mutually exclusive):
- Document and use AWS-stored secrets
- Have localdev overrides for easier use
- Have localdev disables or what not.
- ???

### PR DESCRIPTION
**Pull request by ryan-roemer**
## Big
- Major refactor of the application code to `async` pattern with actual error handling. Previously any errors were just swallowed in promises due to promise coding and cache header setting. This resulted in a given page hanging instead of throwing an error page. Fixes #27 
- Move all `res.*` setting methods to one location that occurs _after_ we do all the stuff that can throw exceptions. Even with proper `async` error handling if you set headers the responses will still hang.
- Add localdev example for using prod secrets. Fixes #28 
- Redirect index page to Formidable lander. Fixes #23 
- Update PR comment to hopefully 🤞 give us clickable + SVG example badges!

## Small
- Replace `console.log` with `debug` for localdev
- Remove referrer logging.
- Remove old `require.main` script testing that applied against old project.

## Review note

The diff for `src/index.js` is collapsed because it's large. Unfortunately, it's also the most important thing to review because I changed so much!

/cc @tptee @exogen @formidableamy

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -32,43 +33,39 @@ const {
...
+    labels: req.query.labels,
+    exclude: req.query.exclude,
+    sortBy: req.query.sortBy,
+    versionDivider: req.query.versionDivider,
+    ...query
+  };
+
+  let browsers;
+  try {
+    browsers = await Promise.resolve(getBrowsers);
```
Comment (tptee) [inline src/index.js]: Do we need the `Promise.resolve` here? I think `getBrowsers` is already a Promise, so we can just `await` it?

File: src/index.js [hunk 2]
```diff
@@ -77,70 +74,85 @@ function handleBrowsersBadge(req, res, browsersList) {
...
-function handleSauceBadge(req, res, client, source, sauceJobs) {
-  let browsers;
+const getSauceBadgeBody = ({ req, sauce, source, sauceJobs }) => {
+  let getBrowsers;
   if (source === 'svg') {
-    browsers = client.getLatestSVGBrowsers();
+    getBrowsers = sauce.getLatestSVGBrowsers();
   } else {
-    browsers = Promise.resolve(sauceJobs).then(jobs => {
+    getBrowsers = Promise.resolve(sauceJobs).then(jobs => {
```
Comment (tptee) [inline src/index.js]: Same re: `Promise.resolve` here

File: src/index.js [hunk 3]
```diff
@@ -77,70 +74,85 @@ function handleBrowsersBadge(req, res, browsersList) {
  * - /sauce/:user - Get jobs for any build (regardless of CI service).
  * - /travis/:user/:repo/sauce - Get jobs for a Travis build.
  */
-// eslint-disable-next-line max-params
-function handleSauceBadge(req, res, client, source, sauceJobs) {
-  let browsers;
+const getSauceBadgeBody = ({ req, sauce, source, sauceJobs }) => {
```
Comment (tptee) [inline src/index.js]: Feel like this function could use some `async/await` magic, but it's not urgent!

File: src/index.js [hunk 4]
```diff
@@ -156,161 +168,139 @@ app.get('/travis.org/*', (req, res, next) => {
...
+    }
 
-app.get('/travis/:user/:repo/sauce/:sauceUser?', (req, res) => {
-  res.status(200);
-  res.set('Content-Type', 'image/svg+xml');
-  if (cachingEnabled) {
-    res.set('Cache-Control', cacheHeader);
-  }
-  res.flushHeaders();
+    sendResponse({ res, body });
```
Comment (tptee) [inline src/index.js]: Dumb question here: if `body` is a Promise, does the `asyncMiddleware` automatically resolve it?

File: src/index.js [hunk 5]
```diff
@@ -156,161 +168,139 @@ app.get('/travis.org/*', (req, res, next) => {
...
 
-app.get('/browsers', (req, res) => {
-  res.status(200);
-  res.set('Content-Type', 'image/svg+xml');
-  if (cachingEnabled) {
-    res.set('Cache-Control', cacheHeader);
-  }
-  res.flushHeaders();
+    const body = await getFileSize(url, options)
+      .then(size => getShieldsBadge(label, size, color, query))
```
Comment (tptee) [inline src/index.js]: Any advantage of the promise chain here vs. `try/catch`?

File: src/index.js (hunk 1 above)
Comment (ryan-roemer) [reply src/index.js]: If my reading was correct, it can be an object as well. I found this in index.js:

```js
const getBrowsers = getGroupedBrowsers(browsers);
```

and `getGroupedBrowsers` returns an object.

Comment (tptee) [reply src/index.js]: Aha, that makes sense now!

File: src/index.js (hunk 3 above)
Comment (ryan-roemer) [reply src/index.js]: Yeah, totally. I got nervous refactoring it more since most of the logic is constructing that `getBrowsers` promise (definitely a promise in this context 😉 ).

File: src/index.js (hunk 4 above)
Comment (ryan-roemer) [reply src/index.js]: `body` isn't a promise. It's the fully finished payload.

File: src/index.js (hunk 5 above)
Comment (ryan-roemer) [reply src/index.js]: Great question! I was originally refactoring it, but catching two separate async calls in a promise chain seemed easier. Otherwise, I'd have a big try catch with two `let` variables outside that just seemed messier...

Happy to change if you think better?

Comment (tptee) [reply src/index.js]: ew, yeah I see that now 😂 better as-is

File: src/index.js [hunk 6]
```diff
@@ -156,161 +168,139 @@ app.get('/travis.org/*', (req, res, next) => {
...
-  const repo = req.params.repo;
-  const endpoint = res.locals.travisEndpoint || undefined;
-  const sauceUser = req.params.sauceUser || user;
-  const branch = req.query.branch || 'master';
-  const travis = new TravisClient(user, repo, endpoint);
-  // eslint-disable-next-line promise/catch-or-return
-  getSecret('sauce-access-key').then(accessKey => {
+    const accessKey = await getSecret('sauce-access-key');
+    const travis = new TravisClient(user, repo, endpoint);
+    const build = await travis.getLatestBranchBuild(branch);
```
Comment (exogen) [inline src/index.js]: Would this be sped up at all by awaiting in parallel with `getSecret` above? Looks like `accessKey` isn't used until after this.

Comment (ryan-roemer) [reply src/index.js]: Yep, I believe so!

File: src/index.js (hunk 4 above)
Comment (exogen) [reply src/index.js]: I have the same question actually, it sure looks like `getShieldsBadge` returns the result of `cachedRequest` which is a Promise

Comment (ryan-roemer) [reply src/index.js]: Oh, yeah I see the context here. Weird!

I'm adding `await `s as that is definitely more correct.
